"""create table user_bots

Revision ID: c2ca1e44dc77
Revises: 4b7f6ee4eb1b
Create Date: 2024-05-13 16:15:04.730052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ca1e44dc77'
down_revision: Union[str, None] = '4b7f6ee4eb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bots',
    sa.Column('bot_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_prof_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dialogue_id', sa.BigInteger(), nullable=False),
    sa.Column('number_dialogue', sa.BigInteger(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_prof_id'], ['user_profile.user_prof_id'], name=op.f('fk_user_bots_user_prof_id_user_profile'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bot_id', name=op.f('pk_user_bots'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bots')
    # ### end Alembic commands ###
