"""

Revision ID: 30c4643caa94
Revises: 84c8ebd2aab3
Create Date: 2024-05-14 22:38:58.699553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c4643caa94'
down_revision: Union[str, None] = '84c8ebd2aab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_models',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('user_prof_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('dialogue_id', sa.BigInteger(), nullable=False),
    sa.Column('number_dialogue', sa.BigInteger(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_prof_id'], ['user_profile.user_prof_id'], name=op.f('fk_user_models_user_prof_id_user_profile'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_models'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_models')
    # ### end Alembic commands ###
