"""

Revision ID: 84c8ebd2aab3
Revises: 2ef2d5796f23
Create Date: 2024-05-14 22:35:36.515899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c8ebd2aab3'
down_revision: Union[str, None] = '2ef2d5796f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_models',
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_prof_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dialogue_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('number_dialogue', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('current', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_prof_id'], ['user_profile.user_prof_id'], name='fk_user_bots_user_prof_id_user_profile', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', name='pk_user_bots')
    )
    # ### end Alembic commands ###
