"""create payment

Revision ID: 0b63caf22a96
Revises: ffcd405ed827
Create Date: 2024-05-24 16:09:25.531506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b63caf22a96'
down_revision: Union[str, None] = 'ffcd405ed827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payments',
    sa.Column('payment_id', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('user_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=255), nullable=False),
    sa.Column('recipient_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('income_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_details', sa.String(length=255), nullable=True),
    sa.Column('receipt_registration', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_tg_id'], ['user_profile.user_tg_id'], name=op.f('fk_user_payments_user_tg_id_user_profile'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_user_payments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_payments')
    # ### end Alembic commands ###
