"""

Revision ID: adbe409cf480
Revises: 7deafdd2fb32
Create Date: 2024-05-16 15:22:36.899061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adbe409cf480'
down_revision: Union[str, None] = '7deafdd2fb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_models", "dialogue_id", server_default=sa.text("0"))
    op.alter_column("user_models", "number_dialogue", server_default=sa.text("0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
