"""create table user profile

Revision ID: 4b7f6ee4eb1b
Revises: fa2b50b3262a
Create Date: 2024-05-12 21:50:50.169480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7f6ee4eb1b'
down_revision: Union[str, None] = 'fa2b50b3262a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('user_prof_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_prof_id'], ['users.user_tg_id'], name=op.f('fk_user_profile_user_prof_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_prof_id', name=op.f('pk_user_profile'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
